group: deprecated-2017Q2
sudo: required
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

before_install:
  # Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget -q https://root.cern.ch/download/root_v6.14.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf root_v6.14.00.Linux-ubuntu14-x86_64-gcc4.8.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/root/bin/thisroot.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd && wget -q https://www.dropbox.com/s/8hxjkd6twdsv5fi/geant4_install_new.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf geant4_install_new.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source ~/geant4_install/share/Geant4-10.1.2/geant4make/geant4make.sh; fi

  # Dumping stuff for check
  - root-config --version

  # Install NPData needed to run examples suite
  - cd $NPTOOL
  - git clone https://github.com/adrien-matta/NPData

install:

script:
  - cmake --version
  - cd $NPTOOL/NPLib 
  - cmake -GNinja ./
  - ninja install 
  - ./scripts/RootLogon.sh 
  - ./scripts/test/all.sh

after_success:

branches:
  only:
    - NPTool.2.dev

addons:
  apt:
    packages:
    - ninja-build
    - libafterimage0

#notifications:
#  email:
#    recipients:
#      - support@nptool.org
#    on_success: change
#    on_failure: always
